### ISSUE TITLE
Voting, Merging, and Tagging

### ISSUE THREAD

**Issue by tannernelson** [open-swift/docs#5]
Open Swift is growing! We have over 40 members in the Slack now, multiple projects supporting our standards, and even more adding support.

As the popularity of Open Swift continues to grow and the community starts to depend on us, we need to ensure a fair and open policy for voting on issues, merging pull requests, and tagging.

I'm proposing the following rules:
- Decisions are made on Tuesday:
    - Pull requests are merged / closed.
    - Solved Issues are closed.
    - Tags are created (if code was merged).
    - Decisions can be post-poned for another week.
- Voting happens on GitHub:
    - When a debate starts in Slack, we move it to an issue.
    - Solutions can receive thumbs up from supporters (no thumbs down, no double voting).
- Tag creation:
    - Breaking changes **always** receive a major (or minor for projects on 0 majors) bump regardless of how small they are. 
- Focused PRs:
    - To facilitate the voting process, PRs should be as focused as possible on one idea. Splitting separable ideas into multiple PRs is recommended. 

Following the conventions described by this issue, it will remain open until Tuesday April 19th when the final decision will be made based on comments from the community. 

(Thumbs up this comment if you support)

**Comment by paulofaria** [comment]
why tuesday?

**Comment by tannernelson** [comment]
https://en.wikipedia.org/wiki/Patch_Tuesday

**Comment by paulofaria** [comment]
shouldn't it be Minot Tuesday then? :trollface:

**Comment by paulofaria** [comment]
I'm cool with that! If people are sure to be present on Tuesdays. (:

**Comment by tannernelson** [comment]
The hope is that people will have submitted their opinions before the Tuesday.

**Comment by paulofaria** [comment]
I would add
- Have very focused PRs

**Comment by paulofaria** [comment]
something like that

**Comment by paulofaria** [comment]
Also I'm not sure we should tag every merge.

**Comment by tannernelson** [comment]
@paulofaria This only mentions appropriately tagging breaking changes.

**Comment by dreymonde** [comment]
I support @paulofaria that we shouldn’t create tags every Tuesday. I think it will be nice to have a «one snapshot — one tag» rule for the most cases.

**Comment by tannernelson** [comment]
@dreymonde This issue does not recommend creating tags _every_ Tuesday. The only rule stated is to follow semantic versioning when making breaking changes. 

Is there some wording I should make more clear?

**Comment by dreymonde** [comment]
@tannernelson yes, I support you on that completely. I thought that that is a workflow description of every Tuesday:
> Decisions are made on Tuesday:
Issues are closed.
Pull requests are merged / closed.
Tags are created.
Decisions can be post-poned for another week.

Maybe you should write «Decisions can be made only on Tuesday» or something like that.

**Comment by czechboy0** [comment]
See https://github.com/open-swift/docs/blob/master/WORKFLOW.md
